// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero/BoldData.tsx": () => import("../components/mockups/hero/BoldData.tsx"),
  "./components/mockups/hero/ImmersiveDark.tsx": () => import("../components/mockups/hero/ImmersiveDark.tsx"),
  "./components/mockups/hero/ProductForward.tsx": () => import("../components/mockups/hero/ProductForward.tsx")
};
